#include <stdint.h>
#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

int main(){
	uint32_t term1 = 1;
	uint32_t term2 = 1;
	uint32_t next;
	uint32_t sum = 0;

	do{
		next = term2 + term1;

		if(next % 2 == 0)
			sum += next;

		term1 = term2;
		term2 = next;

	} while(next < 4000000);

	printf("Total sum of even-valued numbers is: %u", sum);

	return 0;
}